name: dbt CI

on:
on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dbt
        run: |
          pip install dbt-core==1.12.4 dbt-snowflake==1.12.0

      - name: Create dbt profile
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          mkdir -p ~/.dbt

          cat > ~/.dbt/profiles.yml <<EOF
          reddy_insurance_dbt:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${SNOWFLAKE_ACCOUNT}
                user: ${SNOWFLAKE_USER}
                password: "${SNOWFLAKE_PASSWORD}"
                role: ${SNOWFLAKE_ROLE}
                database: ${SNOWFLAKE_DATABASE}
                warehouse: ${SNOWFLAKE_WAREHOUSE}
                schema: STAGING
                threads: 4
          EOF

      - name: dbt debug
        run: dbt debug

      - name: dbt build
        run: dbt build
